AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation template for Roman Numrals web application
  
#Parameters:
  
Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and SSH for webserver
      GroupName: Roman-Numrals-Sec-Grp
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  
    WebServerHost:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: ami-0b5eea76982371e91
        InstanceType: t2.micro
        KeyName: AdminNodehouse
        SecurityGroupIds:
          - !Ref WebServerSecurityGroup
        Tags:
          - Key: Name
            Value: RomanNumSrv
        UserData: 
          Fn::Base64: 
          |
  
#Outputs: