AWSTemplateFormatVersion: 2010-09-09
Description: |
  
#Parameters:
  
Resources:

  rRomNumsvr:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b5eea76982371e91
      InstanceType: t2.micro
      KeyName: AdminNodehouse
      SecurityGroupIds: 
        - sg-08b66de59cc196c1b
      Tags: 
        - Key: Name
          Value: RomanNums
      UserData:
        Fn::Base64:
        |
          #!/bin/bash
          sudo yum update -y
          sudo yum install httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd
          sudo yum install python3 -y
          sudo pip3 install flask
          sudo yum install git -y
          cd /home/ec2-user
          wget -P templates https://github.com/clarusway/clarusway-aws-devops-13/blob/main/aws/projects/Project-001-Roman-Numerals-Converter/templates/index.html
          wget -P templates https://github.com/clarusway/clarusway-aws-devops-13/blob/main/aws/projects/Project-001-Roman-Numerals-Converter/templates/result.html

#Outputs: